// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateScrollArea('frontScrollArea', { hasVerticalScrollbar: true, scrollbarDivSize: 18, autoHideScrollbars: true, scrollbarMargin: 6, spacing: 4 });
    CreateButton('events', { leftImageWidth: 5, onclick: 'showEvents', rightImageWidth: 1, text: 'Events' });
    CreateButton('toDoItems', { leftImageWidth: 1, onclick: 'showToDoItems', rightImageWidth: 5, text: 'To Do Items' });
    CreateInfoButton('infobutton', { foregroundStyle: 'white', frontID: 'front', onclick: 'showBack', backgroundStyle: 'black' });
    CreateScrollArea('backScrollArea', { hasVerticalScrollbar: true, scrollbarDivSize: 18, autoHideScrollbars: true, scrollbarMargin: 6, spacing: 4 });
    CreateGlassButton('done', { onclick: 'showFront', text: 'Done' });
    CreateText('warning', { text: 'One or more calendars must be selected.' });
    CreateIndicator('indicator', { onValue: 1, criticalValue: 15, value: 15, warningValue: 10 });
}
window.addEventListener('load', setupParts, false);
