/*
  	File:		stdwin.h

	Written by: Keith Gurganus

	GraphicImporter.exe is a MDI application that demonstates QuickTime graphic import 
	functions.This is a part of the QuickTime sample source code and is provided as is.

	stdwin.h :  standard includes
	stdwin.pch will be the pre-compiled header
	stdwin.obj will contain the pre-compiled type information

	Copyright:	© 1997 by Apple Computer, Inc., all rights reserved.
*/

#include <windows.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
