// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateText('text', { text: 'String in Preferences:' });
    CreateText('text1', { text: 'Change String:' });
    CreateButton('button', { rightImageWidth: 10, text: 'Set Preference', onclick: 'setString', leftImageWidth: 10 });
    CreateText('syncedString', { text: '[ string from prefs ]' });
    CreateText('syncIndicator', { text: 'STRING FROM SYNC' });
    CreateInfoButton('infobutton', { foregroundStyle: 'white', onclick: 'showBack', backgroundStyle: 'white', frontID: 'front' });
}
window.addEventListener('load', setupParts, false);
