/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apple_dts_SGDemo */

#ifndef _Included_apple_dts_SGDemo
#define _Included_apple_dts_SGDemo
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_dts_SGDemo_FOCUS_TRAVERSABLE_UNKNOWN
#define apple_dts_SGDemo_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef apple_dts_SGDemo_FOCUS_TRAVERSABLE_DEFAULT
#define apple_dts_SGDemo_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef apple_dts_SGDemo_FOCUS_TRAVERSABLE_SET
#define apple_dts_SGDemo_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef apple_dts_SGDemo_TOP_ALIGNMENT
#define apple_dts_SGDemo_TOP_ALIGNMENT 0.0f
#undef apple_dts_SGDemo_CENTER_ALIGNMENT
#define apple_dts_SGDemo_CENTER_ALIGNMENT 0.5f
#undef apple_dts_SGDemo_BOTTOM_ALIGNMENT
#define apple_dts_SGDemo_BOTTOM_ALIGNMENT 1.0f
#undef apple_dts_SGDemo_LEFT_ALIGNMENT
#define apple_dts_SGDemo_LEFT_ALIGNMENT 0.0f
#undef apple_dts_SGDemo_RIGHT_ALIGNMENT
#define apple_dts_SGDemo_RIGHT_ALIGNMENT 1.0f
#undef apple_dts_SGDemo_serialVersionUID
#define apple_dts_SGDemo_serialVersionUID -7644114512714619750LL
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
#undef apple_dts_SGDemo_serialVersionUID
#define apple_dts_SGDemo_serialVersionUID 4613797578919906343LL
/* Inaccessible static: dbg */
#undef apple_dts_SGDemo_INCLUDE_SELF
#define apple_dts_SGDemo_INCLUDE_SELF 1L
#undef apple_dts_SGDemo_SEARCH_HEAVYWEIGHTS
#define apple_dts_SGDemo_SEARCH_HEAVYWEIGHTS 1L
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
/* Inaccessible static: class_00024java_00024awt_00024KeyboardFocusManager */
/* Inaccessible static: systemSyncLWRequests */
#undef apple_dts_SGDemo_OPENED
#define apple_dts_SGDemo_OPENED 1L
/* Inaccessible static: nameCounter */
#undef apple_dts_SGDemo_serialVersionUID
#define apple_dts_SGDemo_serialVersionUID 4497834738069338734LL
/* Inaccessible static: dbg */
/* Inaccessible static: class_00024java_00024awt_00024Window */
/* Inaccessible static: class_00024java_00024awt_00024event_00024WindowListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024WindowFocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024WindowStateListener */
#undef apple_dts_SGDemo_DEFAULT_CURSOR
#define apple_dts_SGDemo_DEFAULT_CURSOR 0L
#undef apple_dts_SGDemo_CROSSHAIR_CURSOR
#define apple_dts_SGDemo_CROSSHAIR_CURSOR 1L
#undef apple_dts_SGDemo_TEXT_CURSOR
#define apple_dts_SGDemo_TEXT_CURSOR 2L
#undef apple_dts_SGDemo_WAIT_CURSOR
#define apple_dts_SGDemo_WAIT_CURSOR 3L
#undef apple_dts_SGDemo_SW_RESIZE_CURSOR
#define apple_dts_SGDemo_SW_RESIZE_CURSOR 4L
#undef apple_dts_SGDemo_SE_RESIZE_CURSOR
#define apple_dts_SGDemo_SE_RESIZE_CURSOR 5L
#undef apple_dts_SGDemo_NW_RESIZE_CURSOR
#define apple_dts_SGDemo_NW_RESIZE_CURSOR 6L
#undef apple_dts_SGDemo_NE_RESIZE_CURSOR
#define apple_dts_SGDemo_NE_RESIZE_CURSOR 7L
#undef apple_dts_SGDemo_N_RESIZE_CURSOR
#define apple_dts_SGDemo_N_RESIZE_CURSOR 8L
#undef apple_dts_SGDemo_S_RESIZE_CURSOR
#define apple_dts_SGDemo_S_RESIZE_CURSOR 9L
#undef apple_dts_SGDemo_W_RESIZE_CURSOR
#define apple_dts_SGDemo_W_RESIZE_CURSOR 10L
#undef apple_dts_SGDemo_E_RESIZE_CURSOR
#define apple_dts_SGDemo_E_RESIZE_CURSOR 11L
#undef apple_dts_SGDemo_HAND_CURSOR
#define apple_dts_SGDemo_HAND_CURSOR 12L
#undef apple_dts_SGDemo_MOVE_CURSOR
#define apple_dts_SGDemo_MOVE_CURSOR 13L
#undef apple_dts_SGDemo_NORMAL
#define apple_dts_SGDemo_NORMAL 0L
#undef apple_dts_SGDemo_ICONIFIED
#define apple_dts_SGDemo_ICONIFIED 1L
#undef apple_dts_SGDemo_MAXIMIZED_HORIZ
#define apple_dts_SGDemo_MAXIMIZED_HORIZ 2L
#undef apple_dts_SGDemo_MAXIMIZED_VERT
#define apple_dts_SGDemo_MAXIMIZED_VERT 4L
#undef apple_dts_SGDemo_MAXIMIZED_BOTH
#define apple_dts_SGDemo_MAXIMIZED_BOTH 6L
/* Inaccessible static: nameCounter */
#undef apple_dts_SGDemo_serialVersionUID
#define apple_dts_SGDemo_serialVersionUID 2673458971256075116LL
/* Inaccessible static: class_00024java_00024awt_00024Frame */
#undef apple_dts_SGDemo_EXIT_ON_CLOSE
#define apple_dts_SGDemo_EXIT_ON_CLOSE 3L
/* Inaccessible static: defaultLookAndFeelDecoratedKey */
/*
 * Class:     apple_dts_SGDemo
 * Method:    makeSGObject
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_apple_dts_SGDemo_makeSGObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     apple_dts_SGDemo
 * Method:    startSG
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_apple_dts_SGDemo_startSG
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
