/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apple_dts_QDCanvas */

#ifndef _Included_apple_dts_QDCanvas
#define _Included_apple_dts_QDCanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_dts_QDCanvas_FOCUS_TRAVERSABLE_UNKNOWN
#define apple_dts_QDCanvas_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef apple_dts_QDCanvas_FOCUS_TRAVERSABLE_DEFAULT
#define apple_dts_QDCanvas_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef apple_dts_QDCanvas_FOCUS_TRAVERSABLE_SET
#define apple_dts_QDCanvas_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef apple_dts_QDCanvas_TOP_ALIGNMENT
#define apple_dts_QDCanvas_TOP_ALIGNMENT 0.0f
#undef apple_dts_QDCanvas_CENTER_ALIGNMENT
#define apple_dts_QDCanvas_CENTER_ALIGNMENT 0.5f
#undef apple_dts_QDCanvas_BOTTOM_ALIGNMENT
#define apple_dts_QDCanvas_BOTTOM_ALIGNMENT 1.0f
#undef apple_dts_QDCanvas_LEFT_ALIGNMENT
#define apple_dts_QDCanvas_LEFT_ALIGNMENT 0.0f
#undef apple_dts_QDCanvas_RIGHT_ALIGNMENT
#define apple_dts_QDCanvas_RIGHT_ALIGNMENT 1.0f
#undef apple_dts_QDCanvas_serialVersionUID
#define apple_dts_QDCanvas_serialVersionUID -7644114512714619750LL
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
/* Inaccessible static: nameCounter */
#undef apple_dts_QDCanvas_serialVersionUID
#define apple_dts_QDCanvas_serialVersionUID -2284879212465893870LL
/*
 * Class:     apple_dts_QDCanvas
 * Method:    _createNSView
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_apple_dts_QDCanvas__1createNSView
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
