/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas */

#ifndef _Included_com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas
#define _Included_com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas
#ifdef __cplusplus
extern "C" {
#endif
#undef com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_FOCUS_TRAVERSABLE_UNKNOWN
#define com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_FOCUS_TRAVERSABLE_DEFAULT
#define com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_FOCUS_TRAVERSABLE_SET
#define com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_TOP_ALIGNMENT
#define com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_TOP_ALIGNMENT 0.0f
#undef com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_CENTER_ALIGNMENT
#define com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_CENTER_ALIGNMENT 0.5f
#undef com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_BOTTOM_ALIGNMENT
#define com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_BOTTOM_ALIGNMENT 1.0f
#undef com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_LEFT_ALIGNMENT
#define com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_LEFT_ALIGNMENT 0.0f
#undef com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_RIGHT_ALIGNMENT
#define com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_RIGHT_ALIGNMENT 1.0f
#undef com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_serialVersionUID
#define com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_serialVersionUID -7644114512714619750LL
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
/* Inaccessible static: nameCounter */
#undef com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_serialVersionUID
#define com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_serialVersionUID -2284879212465893870LL
/*
 * Class:     com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas
 * Method:    paintme
 * Signature: (Ljava/awt/Graphics;)V
 */
JNIEXPORT void JNICALL Java_com_apple_dts_samplecode_jawtexample_NativeDrawnCanvas_paintme
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
