#! /bin/csh -f

killall FancyStickies >& /dev/null
killall SimpleStickies >& /dev/null

rm ~/Library/Application\ Support/SyncExamples/com.mycompany.FancyStickies.xml >& /dev/null
rm ~/Library/Application\ Support/SyncExamples/com.mycompany.SimpleStickies.xml >& /dev/null

/System/Library/PrivateFrameworks/SyncLegacy.framework/Resources/Translator --unregister com.mycompany.FancyStickies
/System/Library/PrivateFrameworks/SyncLegacy.framework/Resources/Translator --unregister com.mycompany.SimpleStickies

killall syncuid >& /dev/null

