// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateButton('startRecordButton', { text: 'Record', onclick: 'startRecording', rightImageWidth: 10, leftImageWidth: 10 });
    CreateButton('stopRecordButton', { text: 'Stop Recording', onclick: 'stopRecording', rightImageWidth: 10, leftImageWidth: 10 });
    CreateInfoButton('infobutton', { foregroundStyle: 'white', frontID: 'front', onclick: 'showBack', backgroundStyle: 'black' });
    CreateText('deviceStatusText', {  });
}
window.addEventListener('load', setupParts, false);
